### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [xtrasee/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
   -Please double check the link to the test-file, it doesn't lead to a "page not found error" on github
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
   -Please double check the link to the test-file, it doesn't lead to a "page not found error" on github
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [ ] Link to test file for bug/input 3
   -Please double check the link to the test-file, it doesn't lead to a "page not found error" on github
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Great job!

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by xtrasee** [comment]
Hello, I'm confused on the feedback. So the link to my test file directly links to my GitHub page where the test file is at but how would I be able to lead to a page where it says page not found error? could I maybe see an example?

**Comment by yahmad3495** [comment]
![image](https://user-images.githubusercontent.com/69169095/153534745-a0b652b9-6a3c-464f-931a-1237e0de33b0.png)
Hello, each of the links send me to this page. I think there might be a simple typo or something like that causing the issue. Another thing you can check is to see if you set those test files with the correct permissions. If you still can't find it please come to office hours or make a piazza post!

**Comment by yahmad3495** [comment]
Looks good! I've updated your score now.
